### ISSUE TITLE
Display window on Chromebook / Chrome OS

### ISSUE THREAD

**Issue by mosenturm** [yoichiro/chrome_mysql_admin#38]
Hi,

as you can see on the attached picture, there is a display issue on Chrome OS / Chromebook. The lower scrollbar is hiding the icons for add, edit, delete and so on.

Best regards
Andreas
![screenshot 2016-01-13 at 13 14 03](https://cloud.githubusercontent.com/assets/1892927/12294070/ec0dee10-b9f7-11e5-81ca-276060ed8d87.png)

**Comment by yoichiro** [comment]
@mosenturm Hmm... I cannot reproduce this problem. Could you provide me more information to reproduce this?

**Comment by mosenturm** [comment]
@yoichiro I use Version "Chrome MySQL Admin version 4.5.0 (C) Yoichiro Tanaka 2014-2015, all rights reserved." on Acer C720 Chromebook 
Version 48.0.2564.81 beta (64-bit)
Plattform 7647.65.0 (Official Build) beta-channel peppy
Firmware Google_Peppy.4389.93.0

My screen resolution is 1366x768. With a resolution of 1536x864 the issue with the bottom scrollbar disappears.

Andreas

**Comment by yoichiro** [comment]
@mosenturm I could reproduce this problem. When the window is resized, the scroll bar is sometimes shown. Especially, when the window size is resized to small, this problem is reproduced on high frequently.

I intend to investigate the cause of this problem... It would be great if you provide me a few days....

**Comment by mosenturm** [comment]
@yoichiro Sorry for delay. Now its working fine! Thank you!
