### ISSUE TITLE
MS Azure connection problems

### ISSUE THREAD

**Issue by chepele** [yoichiro/chrome_mysql_admin#63]
Hi Yoichiro,

Have porblems with connection on azure.com as I've tested the connection to the base and it is ok, but your application wrote me -188 (TIME that the Connection timed up). Could you please advise what to do?

Thank you in advance.

**Comment by yoichiro** [comment]
@chepele If you can access to your database with the `mysql` client command, you should be able to access to the same database with this app, I guess.

**Comment by yoichiro** [comment]
@chepele I have fixed this issue on the version 4.7.0. Actually, the previous version cannot connect to the Azure MySQL server, because the MySQL Protocol version 10 was not supported. In the new version, I implemented the request/response for Auth Switch (Azure MySQL server requests the negotiation).
